### ISSUE TITLE
dtostrf missing RedBoard_Turbo when it exists for Arduino Uno

### ISSUE THREAD

**Issue by alohawild** [sparkfun/RedBoard_Turbo#2]
I discovered I could not compile my code that coverts numbers to string. I had to instead find the code on the Internet and build it in myself. I think this should be built in.

Here is the code:

```
char * dtostrf(double number, signed char width, unsigned char prec, char *s) {

    if(isnan(number)) {
        strcpy(s, "nan");
        return s;
    }
    if(isinf(number)) {
        strcpy(s, "inf");
        return s;
    }

    if(number > 4294967040.0 || number < -4294967040.0) {
        strcpy(s, "ovf");
        return s;
    }
    char* out = s;
    // Handle negative numbers
    if(number < 0.0) {
        *out = '-';
        ++out;
        number = -number;
    }

    // Round correctly so that print(1.999, 2) prints as "2.00"
    double rounding = 0.5;
    for(uint8_t i = 0; i < prec; ++i)
        rounding /= 10.0;

    number += rounding;

    // Extract the integer part of the number and print it
    unsigned long int_part = (unsigned long) number;
    double remainder = number - (double) int_part;
    out += sprintf(out, "%d", int_part);

    // Print the decimal point, but only if there are digits beyond
    if(prec > 0) {
        *out = '.';
        ++out;
    }

    while(prec-- > 0) {
        remainder *= 10.0;
        if((int)remainder == 0){
                *out = '0';
                 ++out;
        }
    }
    sprintf(out, "%d", (int) remainder);

    return s;
}
```

**Comment by awende** [comment]
The RedBoard Turbo uses the [uf2 bootloader](https://github.com/microsoft/uf2-samdx1) which was created and maintained by Microsoft. But looking into the issue I found that the dtostrf() function does not seem to work with any of the SAMD boards (tested with the Arduino/Genuino Zero board definition).

To get it working, you just need to add the library at the top of your sketch with any other libraries you may be using. Specifically, adding the following at the top of your sketch will get it to work. 

`#include <avr/dtostrf.h>`

**Comment by alohawild** [comment]
I like that better than copying in the code. Thanks for looking into this so fast. We can leave this as the solution so if anyone else has the issue they can see this here
